[package]
name = "gravity"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.53"
getset = "0.1.2"
time = { version = "0.3.7", features = ["serde-well-known"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.78"
