[package]
name = "gravity-binary"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/tisonkun/gravity"
description = "Executables for the Gravity project."

[dependencies]
